export default  {
  $schema: './node_modules/oxlint/configuration_schema.json',
  plugins: [
    'eslint',
    'unicorn',
    'oxc',
    'jsdoc',
    'import',
    'vitest',
  ],
  ignorePatterns: [
    // Directories
    '.idea/**',
    '.vscode/**',
    'dist/**',
    'node_modules/**',
    'coverage/**',
    // Files
    '*.ts',
    '.DS_Store',
    '*.log',
    '.env*',
    'package-lock.json',
    'bun.lockb',
    // To lint files and folders with names starting with a dot
    '!.*'
  ],
  categories: {
    correctness: 'error',
    suspicious: 'warn',
    pedantic: 'off',
  },
  env: {
    builtin: true,
    browser: true,
    node: true,
    vitest: true,
  },
  overrides: [
    {
      files: ['**/*.{js,jsx,cjs,mjs}'],
      rules: {
        // eslint
        'accessor-pairs': 'error',
        'array-callback-return': 'error',
        'block-scoped-var': 'error',
        'curly': ['error', 'multi-line'],
        'default-param-last': 'error',
        'eqeqeq': 'error',
        'func-name-matching': 'error',
        'func-names': ['error', 'as-needed'],
        'grouped-accessor-pairs': 'error',
        'init-declarations': ['error', 'always'],
        'max-classes-per-file': ['error', { max: 1 }],
        'new-cap': 'off',
        'no-alert': 'error',
        'no-array-constructor': 'error',
        'no-duplicate-imports': 'error',
        'no-else-return': 'error',
        'no-empty-file': 'off',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-fallthrough': 'error',
        'no-implicit-coercion': 'error',
        'no-implicit-globals': 'error',
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-multi-assign': 'error',
        'no-multi-str': 'error',
        'no-new': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-object-constructor': 'error',
        'no-param-reassign': 'error',
        'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
        'no-promise-executor-return': 'error',
        'no-proto': 'error',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-return-assign': 'off',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-shadow': 'warn',
        'no-undef': 'error',
        'no-underscore-dangle': 'warn',
        'no-unexpected-multiline': 'error',
        'no-unmodified-loop-condition': 'error',
        'no-unneeded-ternary': 'error',
        'no-unreachable-loop': 'error',
        'no-unused-vars': 'warn',
        'no-use-before-define': ['error', {
          functions: false,
          classes: true,
          variables: true,
          allowNamedExports: false
        }],
        'no-useless-assignment': 'warn',
        'no-useless-call': 'error',
        'no-useless-computed-key': 'error',
        'no-useless-concat': 'error',
        'no-useless-constructor': 'error',
        'no-useless-escape': 'off', // Found issues in regex when used in a template string in RegExp()
        'no-useless-return': 'error',
        'no-var': 'error',
        'no-void': ['error', { allowAsStatement: true }],
        'object-shorthand': ['error', 'consistent-as-needed'],
        'operator-assignment': ['error', 'always'],
        'prefer-arrow-callback': 'error',
        'prefer-const': 'error',
        'prefer-destructuring': 'warn',
        'prefer-object-has-own': 'error',
        'prefer-object-spread': 'error',
        'prefer-promise-reject-errors': 'error',
        'prefer-regex-literals': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'prefer-template': 'warn',
        'preserve-caught-error': 'error',
        'require-await': 'warn',
        'require-unicode-regexp': 'error',
        'sort-imports': [
          'error', { ignoreCase: true, ignoreDeclarationSort: true }
        ],
        'symbol-description': 'error',
        'unicode-bom': ['error', 'never'],
        'vars-on-top': 'error',
        'yoda': ['error', 'never'],
        // import
        'import/default': 'error',
        'import/export': 'warn',
        'import/exports-last': 'off',
        'import/extensions': 'off',
        'import/first': 'error',
        'import/group-exports': 'off',
        'import/named': 'error',
        'import/namespace': 'error',
        'import/newline-after-import': 'error',
        'import/no-amd': 'error',
        'import/no-commonjs': 'error',
        'import/no-cycle': 'error',
        'import/no-duplicates': 'error',
        'import/no-mutable-exports': 'error',
        'import/no-named-as-default': 'error',
        'import/no-named-as-default-member': 'error',
        'import/no-named-default': 'error',
        'import/no-self-import': 'error',
        // jsdoc
        'jsdoc/check-access': 'error',
        'jsdoc/check-property-names': 'error',
        'jsdoc/check-tag-names': [
          'error',
          { definedTags: ['preserve', 'strict'] }
        ],
        'jsdoc/empty-tags': 'error',
        'jsdoc/implements-on-classes': 'error',
        'jsdoc/require-param': 'error',
        'jsdoc/require-param-description': 'off',
        'jsdoc/require-param-name': 'error',
        'jsdoc/require-param-type': 'error',
        'jsdoc/require-property': 'error',
        'jsdoc/require-property-description': 'off',
        'jsdoc/require-property-name': 'error',
        'jsdoc/require-property-type': 'error',
        'jsdoc/require-returns': 'warn',
        'jsdoc/require-returns-description': 'off',
        'jsdoc/require-returns-type': 'error',
        'jsdoc/require-throws-description': 'off',
        'jsdoc/require-throws-type': 'error',
        'jsdoc/require-yields': 'error',
        'jsdoc/require-yields-description': 'off',
        'jsdoc/require-yields-type': 'error',
        // unicorn
        'unicorn/catch-error-name': ['error', { name: 'error' } ],
        'unicorn/consistent-assert': 'error',
        'unicorn/consistent-date-clone': 'error',
        'unicorn/consistent-empty-array-spread': 'error',
        'unicorn/consistent-existence-index-check': 'error',
        'unicorn/consistent-function-scoping': 'error',
        'unicorn/consistent-template-literal-escape': 'error',
        'unicorn/custom-error-definition': 'error',
        'unicorn/error-message': 'error',
        'unicorn/explicit-length-check': 'error',
        'unicorn/explicit-timer-delay': 'error',
        'unicorn/no-array-for-each': 'error',
        'unicorn/no-array-method-this-argument': 'error',
        'unicorn/no-confusing-array-with': 'error',
        'unicorn/no-console-spaces': 'warn',
        'unicorn/no-immediate-mutation': 'error',
        'unicorn/no-instanceof-array': 'error',
        'unicorn/no-negation-in-equality-check': 'error',
        'unicorn/no-new-buffer': 'error',
        'unicorn/no-useless-switch-case': 'error',
        'unicorn/numeric-separators-style': 'error',
        'unicorn/prefer-array-find': 'error',
        'unicorn/prefer-at': 'error',
        'unicorn/prefer-blob-reading-methods': 'error',
        'unicorn/prefer-class-fields': 'error',
        'unicorn/prefer-classlist-toggle': 'error',
        'unicorn/prefer-code-point': 'error',
        'unicorn/prefer-date-now': 'error',
        'unicorn/prefer-default-parameters': 'error',
        'unicorn/prefer-dom-node-append': 'warn',
        'unicorn/prefer-dom-node-dataset': 'error',
        'unicorn/prefer-dom-node-remove': 'warn',
        'unicorn/prefer-dom-node-text-content': 'error',
        'unicorn/prefer-event-target': 'error',
        'unicorn/prefer-export-from': 'warn',
        'unicorn/prefer-global-this': 'error',
        'unicorn/prefer-import-meta-properties': 'error',
        'unicorn/prefer-includes': 'error',
        'unicorn/prefer-keyboard-event-key': 'error',
        'unicorn/prefer-math-min-max': 'error',
        'unicorn/prefer-modern-dom-apis': 'error',
        'unicorn/prefer-modern-math-apis': 'error',
        'unicorn/prefer-negative-index': 'error',
        'unicorn/prefer-node-protocol': 'error',
        'unicorn/prefer-number-coercion': 'error',
        'unicorn/prefer-object-from-entries': 'error',
        'unicorn/prefer-optional-catch-binding': 'error',
        'unicorn/prefer-prototype-methods': 'error',
        'unicorn/prefer-regexp-test': 'error',
        'unicorn/prefer-response-static-json': 'error',
        'unicorn/prefer-single-call': 'error',
        'unicorn/prefer-string-raw': 'error',
        'unicorn/prefer-string-replace-all': 'error',
        'unicorn/prefer-string-slice': 'error',
        'unicorn/prefer-string-trim-start-end': 'error',
        'unicorn/prefer-structured-clone': 'error',
        'unicorn/prefer-ternary': 'error',
        'unicorn/prefer-type-error': 'error',
        'unicorn/throw-new-error': 'error',
        // oxc
        'oxc/branches-sharing-code': 'error',
      },
    },
    {
      files: [
        '**/*.{test,spec}.{js,jsx,cjs,mjs}'
      ],
      rules: {
        'vitest/expect-expect': 'error',
        'vitest/no-commented-out-tests': 'error',
        'vitest/no-conditional-expect': 'error',
        'vitest/no-disabled-tests': 'warn',
        'vitest/no-focused-tests': 'error',
        'vitest/no-identical-title': 'error',
        'vitest/no-import-node-test': 'error',
        'vitest/no-interpolation-in-snapshots': 'error',
        'vitest/no-mocks-import': 'error',
        'vitest/no-standalone-expect': 'error',
        'vitest/no-unneeded-async-expect-function': 'error',
        'vitest/prefer-called-exactly-once-with': 'error',
        'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
        'vitest/valid-describe-callback': 'error',
        'vitest/valid-expect': 'error',
        'vitest/valid-expect-in-promise': 'error',
        'vitest/valid-title': 'off',
        'vitest/consistent-test-it': ['error', { 'fn': 'test' }],
        'vitest/max-expects': 'off',
        'vitest/max-nested-describe': 'off',
        'vitest/no-alias-methods': 'error',
        'vitest/no-conditional-in-test': 'off',
        'vitest/no-conditional-tests': 'error',
        'vitest/no-duplicate-hooks': 'error',
        'vitest/no-hooks': 'off',
        'vitest/no-large-snapshots': 'off',
        'vitest/no-restricted-matchers': 'off',
        'vitest/no-restricted-vi-methods': 'error',
        'vitest/no-test-prefixes': 'error',
        'vitest/no-test-return-statement': 'error',
        'vitest/prefer-each': 'error',
        'vitest/prefer-expect-resolves': 'warn',
        'vitest/prefer-hooks-in-order': 'error',
        'vitest/prefer-hooks-on-top': 'error',
        'vitest/prefer-mock-promise-shorthand': 'error',
        'vitest/prefer-spy-on': 'error',
        'vitest/prefer-strict-equal': 'error',
        'vitest/prefer-to-be': 'error',
        'vitest/prefer-to-be-object': 'error',
        'vitest/prefer-to-contain': 'error',
        'vitest/prefer-todo': 'error',
        'vitest/require-hook': 'error',
        'vitest/require-top-level-describe': 'error'
      }
    }
  ]
}
