# see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
      # setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
      # run
      - run: npm install
      - run: npm run check

  test:
    name: Run Tests
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18.x, 20.x, 21.x, 23.x]

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
      # setup
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # run
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test
